### ISSUE TITLE
Capybara 3.0 TODO list

### ISSUE THREAD

**Issue by abotalov** [abotalov/capybara#1]
- [ ] Change `Simple#text`, `Element#text`, `title` to return normalized strings
- [ ] `TextQuery` shouldn't normalize `@actual_text` as it should be normalized by `text` method
- [ ] `Helpers#to_regexp` shouldn't normalize string
- [ ] Remove unused argument from `Simple#text`
- [ ] `Capybara::Query` should be renamed to `Capybara::Queries::NodeQuery`
- [ ] Remove deprecated code from `Capybara::RSpecMatchers`
- [ ] Remove deprecated ability to pass string to `within_window`
- [ ] All methods that accept options hash should raise an error when invalid keys are passed
- [ ] `assert_text`/`assert_title`/`all` shouldn't ignore other filters if count is specified. Instead all filters should be checked
- [ ] http://stackoverflow.com/questions/24956563/how-to-return-a-value-when-using-execute-script-in-capybara
- [ ] don't define `==` in `Capybara::Node::Matchers` - move to `::Base`
- [ ] `:match` accepts `Integer`
- [ ] Remove some aliases (body, mode)
- [ ] Raise error when not registered selector is passed to `Query` (@selector = Selector.all[args[0]])
- [ ] `warn "Invalid value #{value.inspect} passed to filter #{@name}"`
