### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by abotalov** [abotalov/capybara#2]
- [ ] `Element#set` should have an option not to clear field (https://github.com/jnicklas/capybara/pull/1338)
- [ ] `assert_selector` should be upper in Matchers file
- [ ] Make improvements to assert_selector failure message
- [ ] Deprecate `match` of `add_selector` (Just strange and I don't know if it might be useful)

After getElementAttribute will be changed in Webdriver:
- [ ] Evaluate describes in `Selector`
- [ ] Check if Element#value is nil if it's empty (see Capybara issue 1169)
